{
    "activities":[
        {
            "id":"c67ee496-ed40-4c4f-92d1-111a15ebd4a1",
            "type":"run",
            "app_id":"com.nike.sport.running.ios",
            "start_epoch_ms":1598100242551,
            "end_epoch_ms":1598103120580,
            "last_modified":1598103165931,
            "active_duration_ms":1744181,
            "session":false,
            "delete_indicator":false,
            "summaries":[
                {
                    "metric":"rpe",
                    "summary":"max",
                    "source":"com.nike.running.ios.manualentry",
                    "app_id":"com.nike.sport.running.ios",
                    "value":3
                },
                {
                    "metric":"ascent",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":61.595112800598145
                },
                {
                    "metric":"descent",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":64.46731376647949
                },
                {
                    "metric":"steps",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":4090
                },
                {
                    "metric":"calories",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":294.955
                },
                {
                    "metric":"pace",
                    "summary":"mean",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":7.1847739280580285
                },
                {
                    "metric":"speed",
                    "summary":"mean",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":8.3509934481985
                },
                {
                    "metric":"nikefuel",
                    "summary":"total",
                    "source":"com.nike.nikefuelengine.1.0-A5.0",
                    "app_id":"com.nike.sport.running.ios",
                    "value":1077.587034058253
                },
                {
                    "metric":"distance",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":4.04601225096453
                },
                {
                    "metric":"nikefuel",
                    "summary":"mean",
                    "source":"com.nike.nikefuelengine.1.0-A5.0",
                    "app_id":"com.nike.sport.running.ios",
                    "value":37.06910122487012
                }
            ],
            "sources":[
                "com.nike.pacecalculator.v1",
                "com.nike.running.ios.fullpower",
                "com.nike.running.ios.manualentry",
                "com.nike.nikefuelengine.1.0-A5.0"
            ],
            "tags":{
                "com.nike.name":"Saturday Afternoon Run",
                "com.nike.running.databaseformat":"activeRun",
                "com.nike.running.fullpowerenabled":"false",
                "com.nike.running.goaltype":"distance",
                "com.nike.running.originalactivityid":"FF922964-80A5-4279-A1B5-BFEDDFFC61F1",
                "com.nike.running.recordingappversion":"6.11.0",
                "com.nike.running.recordingsource":"phone",
                "com.nike.running.syncappversion":"6.11.0",
                "com.nike.running.syncsource":"phone",
                "com.nike.temperature":"22.49",
                "com.nike.weather":"partly-cloudy-day",
                "location":"outdoors",
                "shoe_id":"84014958-7d36-4c98-a7ae-64e61ca05373"
            },
            "change_tokens":[
                "6442eda2797ff826fd883a3ebae29475c464ccfa00a073dcc10eda69c39eb083:1598103165931",
                "85b76267b2437da3bb703bdee709eb4f9be2da8b958596f4ff9ec066c7eb21fc:1598103146072",
                "42272196a00f7b04694fac17954e1ec6060a527eec687bcc6689e9d4a00d862e:1598103123777"
            ],
            "metric_types":[
                "elevation",
                "distance",
                "rpe",
                "pace",
                "latitude",
                "calories",
                "steps",
                "speed",
                "nikefuel",
                "descent",
                "ascent",
                "longitude"
            ],
            "metrics":[
                
            ],
            "moments":[
                {
                    "key":"split_km",
                    "value":"1",
                    "timestamp":1598100667250,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"split_km",
                    "value":"2",
                    "timestamp":1598101393420,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"split_km",
                    "value":"3",
                    "timestamp":1598101896156,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"split_km",
                    "value":"4",
                    "timestamp":1598103094735,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"split_mile",
                    "value":"1",
                    "timestamp":1598100915779,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"split_mile",
                    "value":"2",
                    "timestamp":1598101976668,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598100946297,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"resume",
                    "timestamp":1598101234933,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598101312814,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_resume",
                    "timestamp":1598101321542,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598101493646,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_resume",
                    "timestamp":1598101587163,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598102248174,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_resume",
                    "timestamp":1598102743217,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598102750697,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"resume",
                    "timestamp":1598102996591,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"pause",
                    "timestamp":1598103118550,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                }
            ]
        },
        {
            "id":"af6f5932-ff8b-49d6-bca7-29a42f2a18d0",
            "type":"run",
            "app_id":"com.nike.sport.running.ios",
            "start_epoch_ms":1598894017812,
            "end_epoch_ms":1598895230131,
            "last_modified":1598895622633,
            "active_duration_ms":1172087,
            "session":false,
            "delete_indicator":false,
            "summaries":[
                {
                    "metric":"distance",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":3.019154078335967
                },
                {
                    "metric":"calories",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":212.251
                },
                {
                    "metric":"speed",
                    "summary":"mean",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":9.273163751504352
                },
                {
                    "metric":"descent",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":39.936031341552734
                },
                {
                    "metric":"ascent",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":37.99128341674805
                },
                {
                    "metric":"pace",
                    "summary":"mean",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":6.470283671014266
                },
                {
                    "metric":"nikefuel",
                    "summary":"total",
                    "source":"com.nike.nikefuelengine.1.0-A5.0",
                    "app_id":"com.nike.sport.running.ios",
                    "value":785.8782568388503
                },
                {
                    "metric":"rpe",
                    "summary":"max",
                    "source":"com.nike.running.ios.manualentry",
                    "app_id":"com.nike.sport.running.ios",
                    "value":4
                },
                {
                    "metric":"steps",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":2822
                },
                {
                    "metric":"nikefuel",
                    "summary":"mean",
                    "source":"com.nike.nikefuelengine.1.0-A5.0",
                    "app_id":"com.nike.sport.running.ios",
                    "value":40.229688931223556
                }
            ],
            "sources":[
                "com.nike.pacecalculator.v1",
                "com.nike.running.ios.fullpower",
                "com.nike.running.ios.manualentry",
                "com.nike.nikefuelengine.1.0-A5.0"
            ],
            "tags":{
                "com.nike.name":"Monday Evening Run",
                "com.nike.running.databaseformat":"activeRun",
                "com.nike.running.fullpowerenabled":"false",
                "com.nike.running.goaltype":"distance",
                "com.nike.running.originalactivityid":"57AB0739-1A65-42D3-87D9-5F48EBD20EE6",
                "com.nike.running.recordingappversion":"6.11.0",
                "com.nike.running.recordingsource":"phone",
                "com.nike.running.syncappversion":"6.11.0",
                "com.nike.running.syncsource":"phone",
                "location":"outdoors",
                "shoe_id":"84014958-7d36-4c98-a7ae-64e61ca05373"
            },
            "change_tokens":[
                "0ca46781dd59891d8361c3687c754c87f358f36fd0eda2e5b2a97a93d9de365e:1598895622633",
                "c13471e54da43b06204abbf3387fe0a192cbed4e64f44f396fd284b5713577b9:1598895233619",
                "9131b8f927d3b01d80ccdf37e0baacd83ae09dc87f99424dbb350cf99686cfb0:1598895232313"
            ],
            "metric_types":[
                "elevation",
                "distance",
                "rpe",
                "pace",
                "latitude",
                "calories",
                "steps",
                "speed",
                "nikefuel",
                "descent",
                "ascent",
                "longitude"
            ],
            "metrics":[
                
            ],
            "moments":[
                {
                    "key":"split_km",
                    "value":"1",
                    "timestamp":1598894370005,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"split_km",
                    "value":"2",
                    "timestamp":1598894774470,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"split_km",
                    "value":"3",
                    "timestamp":1598895210748,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"split_mile",
                    "value":"1",
                    "timestamp":1598894597022,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598894625898,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_resume",
                    "timestamp":1598894643369,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598894952715,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_resume",
                    "timestamp":1598894960203,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598895195927,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_resume",
                    "timestamp":1598895208400,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"pause",
                    "timestamp":1598895227331,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                }
            ]
        },
        {
            "id":"4a10508c-6c99-4c50-978d-eebdb7969e4a",
            "type":"run",
            "app_id":"com.nike.sport.running.ios",
            "start_epoch_ms":1598984629433,
            "end_epoch_ms":1598985287787,
            "last_modified":1600701845229,
            "active_duration_ms":572818,
            "session":false,
            "delete_indicator":false,
            "summaries":[
                {
                    "metric":"calories",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":96.238
                },
                {
                    "metric":"nikefuel",
                    "summary":"total",
                    "source":"com.nike.nikefuelengine.1.0-A5.0",
                    "app_id":"com.nike.sport.running.ios",
                    "value":392.5641460600795
                },
                {
                    "metric":"steps",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":1306
                },
                {
                    "metric":"speed",
                    "summary":"mean",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":8.573582383387206
                },
                {
                    "metric":"descent",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":22.887775421142578
                },
                {
                    "metric":"pace",
                    "summary":"mean",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":6.998241495440731
                },
                {
                    "metric":"rpe",
                    "summary":"max",
                    "source":"com.nike.running.ios.manualentry",
                    "app_id":"com.nike.sport.running.ios",
                    "value":4
                },
                {
                    "metric":"distance",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":1.3641950871353037
                },
                {
                    "metric":"ascent",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":13.713642120361328
                },
                {
                    "metric":"nikefuel",
                    "summary":"mean",
                    "source":"com.nike.nikefuelengine.1.0-A5.0",
                    "app_id":"com.nike.sport.running.ios",
                    "value":41.11925387052218
                }
            ],
            "sources":[
                "com.nike.pacecalculator.v1",
                "com.nike.running.ios.fullpower",
                "com.nike.running.ios.manualentry",
                "com.nike.nikefuelengine.1.0-A5.0"
            ],
            "tags":{
                "com.nike.name":"Tuesday Evening Run",
                "com.nike.running.databaseformat":"activeRun",
                "com.nike.running.fullpowerenabled":"false",
                "com.nike.running.goaltype":"distance",
                "com.nike.running.originalactivityid":"2655E7B3-79C5-480C-8791-45C6B521523C",
                "com.nike.running.recordingappversion":"6.11.0",
                "com.nike.running.recordingsource":"phone",
                "com.nike.running.syncappversion":"6.11.0",
                "com.nike.running.syncsource":"phone",
                "com.nike.temperature":"18.58",
                "com.nike.weather":"partly-cloudy-day",
                "location":"outdoors",
                "shoe_id":"84014958-7d36-4c98-a7ae-64e61ca05373"
            },
            "change_tokens":[
                "a06f59fc8f09492e14306dc862078f0443f607c50489f9ce00e305cb95561b6a:1600701845229",
                "3a0bf1dce6f1914f0391346159412153fdaf79eab10a6e0972fe6c08130d8e3b:1598985290744",
                "1a29ce6f1e3ecd7d9f8c8fb801153ed53824984384d13e3c4c97954748eb42f8:1598985289435"
            ],
            "metric_types":[
                "elevation",
                "distance",
                "rpe",
                "pace",
                "latitude",
                "calories",
                "steps",
                "speed",
                "nikefuel",
                "descent",
                "ascent",
                "longitude"
            ],
            "metrics":[
                
            ],
            "moments":[
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598984824675,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_resume",
                    "timestamp":1598984872089,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598985046681,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_resume",
                    "timestamp":1598985051666,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1598985081611,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_resume",
                    "timestamp":1598985112800,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"pause",
                    "timestamp":1598985285838,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"split_km",
                    "value":"1",
                    "timestamp":1598985070055,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                }
            ]
        },
        {
            "id":"b26528d1-6d21-4313-a3d0-7edb17d9e4b0",
            "type":"run",
            "app_id":"com.nike.sport.running.ios",
            "start_epoch_ms":1600974098133,
            "end_epoch_ms":1600974604219,
            "last_modified":1600974678157,
            "active_duration_ms":502797,
            "session":false,
            "delete_indicator":false,
            "summaries":[
                {
                    "metric":"steps",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":1216
                },
                {
                    "metric":"speed",
                    "summary":"mean",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":9.1956590329067
                },
                {
                    "metric":"distance",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":1.2843193818801082
                },
                {
                    "metric":"descent",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":16.805160522460938
                },
                {
                    "metric":"calories",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":90.429
                },
                {
                    "metric":"nikefuel",
                    "summary":"total",
                    "source":"com.nike.nikefuelengine.1.0-A5.0",
                    "app_id":"com.nike.sport.running.ios",
                    "value":338.0740804663129
                },
                {
                    "metric":"rpe",
                    "summary":"max",
                    "source":"com.nike.running.ios.manualentry",
                    "app_id":"com.nike.sport.running.ios",
                    "value":4
                },
                {
                    "metric":"pace",
                    "summary":"mean",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":6.524817828204567
                },
                {
                    "metric":"ascent",
                    "summary":"total",
                    "source":"com.nike.running.ios.fullpower",
                    "app_id":"com.nike.sport.running.ios",
                    "value":16.429946899414062
                },
                {
                    "metric":"nikefuel",
                    "summary":"mean",
                    "source":"com.nike.nikefuelengine.1.0-A5.0",
                    "app_id":"com.nike.sport.running.ios",
                    "value":40.34320974066826
                }
            ],
            "sources":[
                "com.nike.pacecalculator.v1",
                "com.nike.running.ios.fullpower",
                "com.nike.running.ios.manualentry",
                "com.nike.nikefuelengine.1.0-A5.0"
            ],
            "tags":{
                "com.nike.name":"Thursday Evening Run",
                "com.nike.running.databaseformat":"activeRun",
                "com.nike.running.fullpowerenabled":"false",
                "com.nike.running.goaltype":"distance",
                "com.nike.running.originalactivityid":"3E76C6F3-431F-4D74-90A2-D6C9C84A1168",
                "com.nike.running.recordingappversion":"6.12.0",
                "com.nike.running.recordingsource":"phone",
                "com.nike.running.syncappversion":"6.12.0",
                "com.nike.running.syncsource":"phone",
                "com.nike.temperature":"11.18",
                "com.nike.weather":"cloudy",
                "location":"outdoors",
                "shoe_id":"84014958-7d36-4c98-a7ae-64e61ca05373"
            },
            "change_tokens":[
                "6d011c2e6411617c123c6f07e9b74d25f6f2a1692daa32b1308328fdb276e80b:1600974678157",
                "628b94c30b8b99f13a29b686b523d096e41c8b8623c0a56b4d2c876e3d505f8f:1600974609078",
                "f0404a50febc19731086375b76688d6739e8cb994282678a7d7e33b8c98ef9dc:1600974607430"
            ],
            "metric_types":[
                "elevation",
                "distance",
                "rpe",
                "pace",
                "latitude",
                "calories",
                "steps",
                "speed",
                "nikefuel",
                "descent",
                "ascent",
                "longitude"
            ],
            "metrics":[
                
            ],
            "moments":[
                {
                    "key":"split_km",
                    "value":"1",
                    "timestamp":1600974484675,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                },
                {
                    "key":"halt",
                    "value":"auto_pause",
                    "timestamp":1600974600930,
                    "app_id":"com.nike.sport.running.ios",
                    "source":"com.nike.running.ios.fullpower"
                }
            ]
        }
    ],
    "paging":{
        "before_time":1597489771823,
        "before_id":"c67ee496-ed40-4c4f-92d1-111a15ebd4a1"
    }
}